use std::fmt;

/// Content Security Policy nonce for style injection.
///
/// When CSP is enabled, style tags must include a nonce attribute
/// matching the CSP header. `CspNonce` generates and manages these nonces
/// for NexusStratum's CSS injection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CspNonce {
    value: String,
}

impl CspNonce {
    /// Create a new CSP nonce from a pre-generated value.
    ///
    /// The nonce should be a cryptographically random base64 string,
    /// typically generated by the server framework (Actix, Axum, etc.).
    pub fn new(value: impl Into<String>) -> Self {
        Self {
            value: value.into(),
        }
    }

    /// Generate a nonce using a simple random approach.
    ///
    /// For production use, prefer `new()` with a nonce from your
    /// server framework's CSP middleware.
    pub fn generate() -> Self {
        // Simple pseudo-random nonce using thread_rng-like approach
        // In production, this should come from the server framework
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let nonce = format!("{:x}{:x}", timestamp, timestamp.wrapping_mul(6364136223846793005));
        Self { value: nonce }
    }

    /// Get the nonce value.
    pub fn value(&self) -> &str {
        &self.value
    }

    /// Generate the `nonce` attribute for a `<style>` tag.
    pub fn style_attr(&self) -> String {
        format!("nonce=\"{}\"", self.value)
    }

    /// Generate the CSP directive for this nonce.
    pub fn csp_directive(&self) -> String {
        format!("'nonce-{}'", self.value)
    }
}

impl fmt::Display for CspNonce {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.value)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csp_nonce_from_value() {
        let nonce = CspNonce::new("abc123");
        assert_eq!(nonce.value(), "abc123");
    }

    #[test]
    fn csp_nonce_style_attr() {
        let nonce = CspNonce::new("test-nonce");
        assert_eq!(nonce.style_attr(), "nonce=\"test-nonce\"");
    }

    #[test]
    fn csp_nonce_directive() {
        let nonce = CspNonce::new("test-nonce");
        assert_eq!(nonce.csp_directive(), "'nonce-test-nonce'");
    }

    #[test]
    fn csp_nonce_generate_unique() {
        let a = CspNonce::generate();
        // Small sleep to ensure different timestamp
        std::thread::sleep(std::time::Duration::from_millis(1));
        let b = CspNonce::generate();
        assert_ne!(a, b);
    }

    #[test]
    fn csp_nonce_display() {
        let nonce = CspNonce::new("display-test");
        assert_eq!(format!("{}", nonce), "display-test");
    }
}
