use std::fmt;

/// Content Security Policy nonce for style injection.
///
/// When CSP is enabled, style tags must include a nonce attribute
/// matching the CSP header. `CspNonce` generates and manages these nonces
/// for NexusStratum's CSS injection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CspNonce {
    value: String,
}

impl CspNonce {
    /// Create a new CSP nonce from a pre-generated value.
    ///
    /// The nonce should be a cryptographically random base64 string,
    /// typically generated by the server framework (Actix, Axum, etc.).
    pub fn new(value: impl Into<String>) -> Self {
        Self {
            value: value.into(),
        }
    }

    /// Generate a cryptographically secure nonce.
    ///
    /// Uses the OS CSPRNG via `getrandom`. For production deployments
    /// behind a server framework with CSP middleware, prefer `new()` with
    /// the framework-provided nonce instead.
    pub fn generate() -> Self {
        Self {
            value: generate_secure_token(24),
        }
    }

    /// Get the nonce value.
    pub fn value(&self) -> &str {
        &self.value
    }

    /// Generate the `nonce` attribute for a `<style>` tag.
    ///
    /// The nonce value is escaped to prevent attribute injection.
    pub fn style_attr(&self) -> String {
        format!("nonce=\"{}\"", stratum_core::security::escape_attr(&self.value))
    }

    /// Generate the CSP directive for this nonce.
    pub fn csp_directive(&self) -> String {
        format!("'nonce-{}'", self.value)
    }
}

impl fmt::Display for CspNonce {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.value)
    }
}

/// Generate a hex-encoded cryptographically secure random token.
pub(crate) fn generate_secure_token(byte_len: usize) -> String {
    let mut buf = vec![0u8; byte_len];
    getrandom::fill(&mut buf).expect("OS CSPRNG should be available");
    buf.iter().map(|b| format!("{:02x}", b)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csp_nonce_from_value() {
        let nonce = CspNonce::new("abc123");
        assert_eq!(nonce.value(), "abc123");
    }

    #[test]
    fn csp_nonce_style_attr() {
        let nonce = CspNonce::new("test-nonce");
        assert_eq!(nonce.style_attr(), "nonce=\"test-nonce\"");
    }

    #[test]
    fn csp_nonce_directive() {
        let nonce = CspNonce::new("test-nonce");
        assert_eq!(nonce.csp_directive(), "'nonce-test-nonce'");
    }

    #[test]
    fn csp_nonce_generate_unique() {
        let a = CspNonce::generate();
        let b = CspNonce::generate();
        assert_ne!(a, b);
        // 24 random bytes = 48 hex chars
        assert_eq!(a.value().len(), 48);
    }

    #[test]
    fn csp_nonce_generate_is_hex() {
        let nonce = CspNonce::generate();
        assert!(nonce.value().chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn csp_nonce_display() {
        let nonce = CspNonce::new("display-test");
        assert_eq!(format!("{}", nonce), "display-test");
    }
}
