use clap::{Parser, Subcommand};
use std::fs;
use std::path::Path;

#[derive(Parser)]
#[command(name = "stratum", about = "NexusStratum CLI — scaffolding, themes, and component management")]
#[command(version, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Initialize NexusStratum in a project
    Init {
        /// Target framework
        #[arg(long, default_value = "leptos")]
        framework: String,
    },
    /// Add a component to your project
    Add {
        /// Component names to add
        components: Vec<String>,
        /// Target framework
        #[arg(long, default_value = "leptos")]
        framework: String,
        /// Add as crate dependency instead of copying source
        #[arg(long)]
        crate_dep: bool,
        /// Add all components
        #[arg(long)]
        all: bool,
    },
    /// Theme management
    Theme {
        #[command(subcommand)]
        command: ThemeCommands,
    },
    /// Show component diff between versions
    Diff {
        /// Component name
        component: String,
        /// From version
        #[arg(long)]
        from: String,
        /// To version
        #[arg(long)]
        to: String,
    },
    /// List all available components
    List,
    /// Open component documentation
    Docs {
        /// Component name
        component: String,
    },
    /// Start the component explorer
    Explorer,
}

#[derive(Subcommand)]
enum ThemeCommands {
    /// List available themes
    List,
    /// Create a new theme
    Create {
        /// Theme name
        name: String,
        /// Base theme
        #[arg(long, default_value = "default")]
        base: String,
    },
    /// Apply a theme to the project
    Apply {
        /// Theme name
        name: String,
    },
}

/// Built-in component registry, organized by category.
const COMPONENT_REGISTRY: &[(&str, &[&str])] = &[
    ("Layout", &["Box", "Stack", "HStack", "VStack", "Grid", "Center", "Container", "Divider", "AspectRatio", "ScrollArea", "Resizable"]),
    ("Typography", &["Text", "Heading", "Code", "Kbd", "Blockquote", "Link"]),
    ("Forms", &["Button", "Checkbox", "Radio", "Switch", "Slider", "Input", "Textarea", "NumberInput", "Select", "Combobox", "DatePicker", "Form"]),
    ("Overlay", &["Dialog", "AlertDialog", "Drawer", "Sheet", "Popover", "Tooltip", "ContextMenu", "HoverCard", "Toast"]),
    ("Navigation", &["Tabs", "Accordion", "NavigationMenu", "Breadcrumb", "Pagination", "Menu", "DropdownMenu"]),
    ("Data Display", &["Table", "DataTable", "VirtualList", "Tree", "Badge", "Tag", "Avatar", "Card", "Progress", "Skeleton", "Spinner"]),
    ("Feedback", &["Alert", "Banner", "EmptyState", "ErrorBoundary"]),
    ("Utility", &["Portal", "VisuallyHidden", "FocusScope", "Separator"]),
];

const BUILT_IN_THEMES: &[&str] = &["default", "slate", "zinc", "rose", "blue", "green", "orange"];

fn find_component(name: &str) -> Option<(&'static str, &'static str)> {
    let lower = name.to_lowercase();
    for (category, components) in COMPONENT_REGISTRY {
        for comp in *components {
            if comp.to_lowercase() == lower {
                return Some((category, comp));
            }
        }
    }
    None
}

fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

fn ensure_stratum_toml() {
    if !Path::new("stratum.toml").exists() {
        eprintln!("Error: stratum.toml not found. Run `stratum init` first.");
        std::process::exit(1);
    }
}

fn component_stub(name: &str, framework: &str) -> String {
    let snake = to_snake_case(name);
    match framework {
        "dioxus" => format!(
            r#"//! {name} component — generated by `stratum add {snake}`
//!
//! Customize this file freely. You own this code.

use stratum_core::render::RenderOutput;
use stratum_core::aria::{{AriaAttributes, AriaRole}};

/// {name} component props.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct {name}Props {{
    pub class: Option<String>,
    pub disabled: bool,
}}

/// {name} component.
pub struct {name};

impl {name} {{
    pub fn render(props: &{name}Props) -> RenderOutput {{
        let aria = AriaAttributes::new();
        RenderOutput::new()
            .with_tag("div")
            .with_class("stratum-{snake}")
            .with_aria(aria)
    }}
}}
"#,
            name = name,
            snake = snake,
        ),
        _ => format!(
            r#"//! {name} component — generated by `stratum add {snake}`
//!
//! Customize this file freely. You own this code.

use stratum_core::render::RenderOutput;
use stratum_core::aria::{{AriaAttributes, AriaRole}};

/// {name} component props.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct {name}Props {{
    pub class: Option<String>,
    pub disabled: bool,
}}

/// {name} component.
pub struct {name};

impl {name} {{
    pub fn render(props: &{name}Props) -> RenderOutput {{
        let aria = AriaAttributes::new();
        RenderOutput::new()
            .with_tag("div")
            .with_class("stratum-{snake}")
            .with_aria(aria)
    }}
}}
"#,
            name = name,
            snake = snake,
        ),
    }
}

fn init_project(framework: &str) {
    if framework != "leptos" && framework != "dioxus" {
        eprintln!("Error: unsupported framework '{}'. Use 'leptos' or 'dioxus'.", framework);
        std::process::exit(1);
    }

    println!("Initializing NexusStratum with framework: {}", framework);

    let stratum_toml = format!(
        r#"[project]
framework = "{}"

[components]
# Components added via `stratum add` are listed here.
added = []

[theme]
name = "default"
dark_mode = "system"

[paths]
components = "src/components"
"#,
        framework
    );

    if Path::new("stratum.toml").exists() {
        println!("  stratum.toml already exists, skipping.");
    } else {
        fs::write("stratum.toml", &stratum_toml).expect("Failed to write stratum.toml");
        println!("  Created stratum.toml");
    }

    if Path::new("Cargo.toml").exists() {
        let contents = fs::read_to_string("Cargo.toml").expect("Failed to read Cargo.toml");
        if !contents.contains("# NexusStratum") {
            let updated = format!(
                "{}\n# NexusStratum: run `stratum add <component>` to add components.\n",
                contents.trim_end()
            );
            fs::write("Cargo.toml", updated).expect("Failed to write Cargo.toml");
            println!("  Added NexusStratum marker to Cargo.toml");
        }
    }

    let components_dir = Path::new("src/components");
    if !components_dir.exists() {
        fs::create_dir_all(components_dir).expect("Failed to create src/components/");
        fs::write(
            components_dir.join("mod.rs"),
            "//! NexusStratum components for this project.\n",
        )
        .expect("Failed to write src/components/mod.rs");
        println!("  Created src/components/mod.rs");
    }

    println!("\nNexusStratum initialized. Add your first component:");
    println!("  stratum add button");
}

fn add_components(components: &[String], framework: &str, crate_dep: bool, all: bool) {
    ensure_stratum_toml();

    let comp_dir = Path::new("src/components");
    if !comp_dir.exists() {
        fs::create_dir_all(comp_dir).expect("Failed to create src/components/");
    }

    let targets: Vec<(&str, &str)> = if all {
        COMPONENT_REGISTRY
            .iter()
            .flat_map(|(cat, comps)| comps.iter().map(move |c| (*cat, *c)))
            .collect()
    } else {
        if components.is_empty() {
            eprintln!("Error: no component names provided. Use `stratum add <name>` or `stratum add --all`.");
            std::process::exit(1);
        }
        components
            .iter()
            .map(|name| {
                find_component(name).unwrap_or_else(|| {
                    eprintln!(
                        "Error: unknown component '{}'. Run `stratum list` to see available components.",
                        name
                    );
                    std::process::exit(1);
                })
            })
            .collect()
    };

    let mut added = Vec::new();
    for (_category, name) in &targets {
        let snake = to_snake_case(name);
        let file_path = comp_dir.join(format!("{}.rs", snake));

        if crate_dep {
            println!("  {} — added as crate dependency (stratum-components)", name);
            added.push(name.to_string());
            continue;
        }

        if file_path.exists() {
            println!("  {} — already exists at {}, skipping.", name, file_path.display());
            continue;
        }

        let source = component_stub(name, framework);
        fs::write(&file_path, source).unwrap_or_else(|e| panic!("Failed to write {}: {}", file_path.display(), e));
        println!("  {} — created {}", name, file_path.display());
        added.push(name.to_string());
    }

    // Update mod.rs with new modules
    let mod_path = comp_dir.join("mod.rs");
    let mut mod_contents = if mod_path.exists() {
        fs::read_to_string(&mod_path).unwrap_or_default()
    } else {
        "//! NexusStratum components for this project.\n".to_string()
    };

    for (_category, name) in &targets {
        let snake = to_snake_case(name);
        let mod_line = format!("pub mod {};", snake);
        if !mod_contents.contains(&mod_line) {
            mod_contents.push_str(&format!("{}\n", mod_line));
        }
    }
    fs::write(&mod_path, mod_contents).expect("Failed to update mod.rs");

    if added.is_empty() {
        println!("\nNo new components added.");
    } else {
        println!("\nAdded {} component(s).", added.len());
    }
}

fn list_components() {
    println!("NexusStratum Components:\n");
    let mut total = 0;
    for (category, components) in COMPONENT_REGISTRY {
        println!("  {} ({})", category, components.len());
        for comp in *components {
            println!("    {}", comp);
        }
        total += components.len();
        println!();
    }
    println!("  Total: {} components", total);
}

fn theme_list() {
    println!("Built-in themes:\n");
    for theme in BUILT_IN_THEMES {
        println!("  {}", theme);
    }
    println!("\nApply with: stratum theme apply <name>");
}

fn theme_create(name: &str, base: &str) {
    ensure_stratum_toml();

    if !BUILT_IN_THEMES.contains(&base) {
        eprintln!(
            "Error: unknown base theme '{}'. Available: {}",
            base,
            BUILT_IN_THEMES.join(", ")
        );
        std::process::exit(1);
    }

    let theme_dir = Path::new("src/theme");
    fs::create_dir_all(theme_dir).expect("Failed to create src/theme/");

    let theme_file = theme_dir.join(format!("{}.rs", name));
    if theme_file.exists() {
        eprintln!("Error: theme '{}' already exists at {}", name, theme_file.display());
        std::process::exit(1);
    }

    let source = format!(
        r#"//! Custom theme: {name}
//! Based on: {base}

use stratum_theme::{{Theme, Hsl}};

pub fn {name}_theme() -> Theme {{
    Theme::{base}()
        // Customize colors:
        // .with_primary(Hsl::new(262.0, 83.0, 58.0), Hsl::new(262.0, 70.0, 68.0))
        // .with_font_sans("'Inter', sans-serif")
}}
"#,
        name = name,
        base = base,
    );

    fs::write(&theme_file, source).expect("Failed to write theme file");
    println!("Created theme '{}' at {}", name, theme_file.display());
    println!("Based on: {}", base);
    println!("\nEdit the file to customize colors, fonts, spacing, and more.");
}

fn theme_apply(name: &str) {
    ensure_stratum_toml();

    let toml_content = fs::read_to_string("stratum.toml").expect("Failed to read stratum.toml");

    let updated = if toml_content.contains("[theme]") {
        let mut in_theme_section = false;
        let mut replaced = false;
        toml_content
            .lines()
            .map(|line| {
                if line.starts_with('[') {
                    in_theme_section = line.trim() == "[theme]";
                }
                if in_theme_section && line.starts_with("name = ") && !replaced {
                    replaced = true;
                    format!("name = \"{}\"", name)
                } else {
                    line.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        format!("{}\n[theme]\nname = \"{}\"\n", toml_content.trim_end(), name)
    };

    fs::write("stratum.toml", updated).expect("Failed to write stratum.toml");
    println!("Applied theme '{}' to stratum.toml", name);
}

fn diff_component(component: &str, from: &str, to: &str) {
    match find_component(component) {
        Some((category, canonical)) => {
            println!("Component: {} ({})", canonical, category);
            println!("Comparing: v{} → v{}", from, to);
            println!();
            println!("Diff is available on GitHub:");
            println!(
                "  https://github.com/AutomataNexus/NexusStratum/compare/v{}...v{} -- crates/stratum-components/src/**/{}",
                from,
                to,
                to_snake_case(canonical)
            );
        }
        None => {
            eprintln!("Error: unknown component '{}'. Run `stratum list`.", component);
            std::process::exit(1);
        }
    }
}

fn docs_component(component: &str) {
    match find_component(component) {
        Some((_category, canonical)) => {
            let snake = to_snake_case(canonical);
            let url = format!("https://stratum-ui.com/components/{}.html", snake);
            println!("Opening docs for {}...", canonical);
            println!("  {}", url);

            // Try to open in browser
            #[cfg(target_os = "linux")]
            { let _ = std::process::Command::new("xdg-open").arg(&url).spawn(); }
            #[cfg(target_os = "macos")]
            { let _ = std::process::Command::new("open").arg(&url).spawn(); }
            #[cfg(target_os = "windows")]
            { let _ = std::process::Command::new("cmd").args(["/c", "start", &url]).spawn(); }
        }
        None => {
            eprintln!("Error: unknown component '{}'. Run `stratum list`.", component);
            std::process::exit(1);
        }
    }
}

fn start_explorer() {
    println!("NexusStratum Component Explorer");
    println!();
    println!("The explorer is a web application that requires building from source:");
    println!();
    println!("  git clone https://github.com/AutomataNexus/NexusStratum.git");
    println!("  cd NexusStratum");
    println!("  cargo run -p stratum-explorer");
    println!();
    println!("Or browse components online at: https://stratum-ui.com/components/");
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Init { framework } => init_project(&framework),
        Commands::Add { components, framework, crate_dep, all } => {
            add_components(&components, &framework, crate_dep, all);
        }
        Commands::Theme { command } => match command {
            ThemeCommands::List => theme_list(),
            ThemeCommands::Create { name, base } => theme_create(&name, &base),
            ThemeCommands::Apply { name } => theme_apply(&name),
        },
        Commands::Diff { component, from, to } => diff_component(&component, &from, &to),
        Commands::List => list_components(),
        Commands::Docs { component } => docs_component(&component),
        Commands::Explorer => start_explorer(),
    }
}
