use std::collections::HashSet;
use std::sync::Mutex;

/// Global registry for CSS class definitions.
/// Collects CSS generated by the `css!` macro and deduplicates by class name.
pub struct StyleRegistry {
    styles: Mutex<Vec<StyleEntry>>,
    registered: Mutex<HashSet<String>>,
}

struct StyleEntry {
    #[allow(dead_code)]
    class_name: String,
    css: String,
}

impl StyleRegistry {
    pub fn new() -> Self {
        Self {
            styles: Mutex::new(Vec::new()),
            registered: Mutex::new(HashSet::new()),
        }
    }

    /// Register a CSS class. Returns `false` if already registered (dedup).
    pub fn register(&self, class_name: &str, css: &str) -> bool {
        let mut registered = self.registered.lock().unwrap();
        if registered.contains(class_name) {
            return false;
        }
        registered.insert(class_name.to_owned());
        drop(registered);

        let mut styles = self.styles.lock().unwrap();
        styles.push(StyleEntry {
            class_name: class_name.to_owned(),
            css: css.to_owned(),
        });
        true
    }

    /// Get all registered CSS as a single string for injection.
    pub fn to_css_string(&self) -> String {
        let styles = self.styles.lock().unwrap();
        styles
            .iter()
            .map(|entry| entry.css.as_str())
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Get the count of registered styles.
    pub fn len(&self) -> usize {
        self.styles.lock().unwrap().len()
    }

    pub fn is_empty(&self) -> bool {
        self.styles.lock().unwrap().is_empty()
    }

    /// Clear all registered styles (for testing).
    pub fn clear(&self) {
        self.styles.lock().unwrap().clear();
        self.registered.lock().unwrap().clear();
    }
}

impl Default for StyleRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Global style registry singleton.
pub static GLOBAL_REGISTRY: std::sync::LazyLock<StyleRegistry> =
    std::sync::LazyLock::new(StyleRegistry::new);
