use std::collections::HashSet;
use std::sync::Mutex;

/// Internal state protected by a single mutex to prevent TOCTOU races.
struct RegistryInner {
    /// Ordered CSS entries for deterministic output.
    entries: Vec<String>,
    /// Set of registered class names for O(1) dedup.
    registered: HashSet<String>,
}

/// Global registry for CSS class definitions.
/// Collects CSS generated by the `css!` macro and deduplicates by class name.
///
/// Uses a single mutex to protect both the entry list and dedup set,
/// preventing TOCTOU races between checking and inserting.
/// Mutex operations recover from poisoning to avoid cascading panics.
pub struct StyleRegistry {
    inner: Mutex<RegistryInner>,
}

impl StyleRegistry {
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(RegistryInner {
                entries: Vec::new(),
                registered: HashSet::new(),
            }),
        }
    }

    /// Get the global singleton registry.
    ///
    /// This is used by the `css!` macro to register styles at runtime.
    pub fn global() -> &'static StyleRegistry {
        &GLOBAL_REGISTRY
    }

    /// Register a CSS class. Returns `false` if already registered (dedup).
    pub fn register(&self, class_name: &str, css: &str) -> bool {
        let mut inner = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        if !inner.registered.insert(class_name.to_owned()) {
            return false;
        }
        inner.entries.push(css.to_owned());
        true
    }

    /// Get all registered CSS as a single string for injection.
    pub fn to_css_string(&self) -> String {
        let inner = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        inner.entries.join("\n")
    }

    /// Get the count of registered styles.
    pub fn len(&self) -> usize {
        self.inner
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .entries
            .len()
    }

    pub fn is_empty(&self) -> bool {
        self.inner
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .entries
            .is_empty()
    }

    /// Clear all registered styles (for testing).
    pub fn clear(&self) {
        let mut inner = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        inner.entries.clear();
        inner.registered.clear();
    }
}

impl Default for StyleRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Global style registry singleton.
pub static GLOBAL_REGISTRY: std::sync::LazyLock<StyleRegistry> =
    std::sync::LazyLock::new(StyleRegistry::new);
